Models/Ledger.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ams.Models
{
    public class Ledger
    {
        [Key]
        public int LedgerID { get; set; }

        [Display(Name = "Date")]
        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime? Date { get; set; }

        public int CustomerId { get; set; }
        public string BillNo { get; set; }
        public string Particular { get; set; }
        public int Debit { get; set; }
        public int Credit { get; set; }
        public int Balance { get; set; }
        public int isCheque { get; set; }
        public int isSeen { get; set; }
    }
}

Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ams.Models;

namespace ams.Controllers
{
    public class CustomerController : Controller
    {
        private AMSDBContext db = new AMSDBContext();

        //
        // GET: /Customer/

        public ActionResult Index()
        {
            return View(db.Customer.OrderBy(x => x.City).ThenBy(y => y.Name).ToList());
        }

        //
        // GET: /Customer/Details/5

        public ActionResult Details(int id = 0)
        {
            Customer customer = db.Customer.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        //
        // GET: /Customer/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Customer/Create

        [HttpPost]
        public ActionResult Create(Customer customer)
        {
            if (ModelState.IsValid)
            {
                customer.PendingDate = DateTime.Now;
                db.Customer.Add(customer);
                db.SaveChanges();

                ////-- ADDING OPENING BALANCE
                //Ledger ledger = new Ledger();
                //ledger.Balance = customer.OpeningBalance;
                //ledger.Date = DateTime.Now;
                //ledger.CustomerId = db.Customer.Max(u => u.CustomerID);
                //ledger.BillNo = "";
                //ledger.Particular = "Opening Balance";
                //ledger.Debit = 0;
                //ledger.Credit = 0;
                //ledger.isCheque = 0;

                //db.Ledger.Add(ledger);
                //db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(customer);
        }

        //
        // GET: /Customer/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Customer customer = db.Customer.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        //
        // POST: /Customer/Edit/5

        [HttpPost]
        public ActionResult Edit(Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(customer);
        }

        //
        // GET: /Customer/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Customer customer = db.Customer.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        //
        // POST: /Customer/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Customer customer = db.Customer.Find(id);
            db.Customer.Remove(customer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
        
        /*
         * 
            AJAX FUNCTIONS HERE
         * 
         */
        public ActionResult TurnOnNotifications(int id)
        {
            Customer c = db.Customer.Find(id);
            c.AlertStatus = 1;
            db.Entry(c).State = EntityState.Modified;
            db.SaveChanges();
            return Json("Request Successful, Notifications for " + c.Name + " are On now");
        }

        public ActionResult TurnOffNotifications(int id)
        {
            Customer c = db.Customer.Find(id);
            c.AlertStatus = 0;
            db.Entry(c).State = EntityState.Modified;
            db.SaveChanges();
            return Json("Request Successful, Notifications for " + c.Name + " are Off now");
        }

        public ActionResult IsNameAvailble(string _Name)
        {
            try
            {
                var tag = db.Customer.Single(x => x.Name == _Name);
                if (tag == null)
                {
                    return Json("Y");
                }
                else
                {
                    return Json("N");
                }
            }
            catch (Exception)
            {
                return Json("Y");
            }
        }
    }
}

Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Reporting.WebForms;
using ams.Models;
using System.Data.SqlClient;
using System.Data.Objects;

namespace ams.Controllers
{
    public class ReportsController : Controller
    {
        private AMSDBContext db = new AMSDBContext();

        //
        // GET: /Reports/

        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /Reporting/CustomerList

        public ActionResult CustomerList()
        {
            LocalReport lr = new LocalReport();
            lr.ReportPath = Server.MapPath("~/Reports/rptCustomers.rdlc");

            List<Customer> ls = new List<Customer>();
            ls = db.Customer.ToList();

            ReportDataSource rd = new ReportDataSource("dtCustomers", ls);
            lr.DataSources.Add(rd);

            string reportType = "pdf";
            string mimeType;
            string encoding;
            string fileNameExtension;
            string deviceInfo =
                "<DeviceInfo>" +
                "  <OutputFormat>PDF</OutputFormat>" +
                "  <PageWidth>8.5in</PageWidth>" +
                "  <PageHeight>11in</PageHeight>" +
                "  <MarginTop>0.5in</MarginTop>" +
                "  <MarginLeft>0.5in</MarginLeft>" +
                "  <MarginRight>0.5in</MarginRight>" +
                "  <MarginBottom>0.5in</MarginBottom>" +
                "</DeviceInfo>";

            Warning[] warnings;
            string[] streams;
            byte[] renderedBytes;

            renderedBytes = lr.Render(reportType, deviceInfo, out mimeType, out encoding, out fileNameExtension, out streams, out warnings);
            return File(renderedBytes, mimeType);
        }

        //
        // GET: /Reporting/CustomerList

        public ActionResult Customer(int id = 0)
        {
            LocalReport lr = new LocalReport();
            lr.ReportPath = Server.MapPath("~/Reports/rptCustomer.rdlc");

            var ls = db.Customer.Select(x => x).Where(z => z.CustomerID == id);
            ReportDataSource rd = new ReportDataSource("dtCustomer", ls.ToList());
            lr.DataSources.Add(rd);

            string reportType = "pdf";
            string mimeType;
            string encoding;
            string fileNameExtension;
            string deviceInfo =
                "<DeviceInfo>" +
                "  <OutputFormat>PDF</OutputFormat>" +
                "  <PageWidth>8.5in</PageWidth>" +
                "  <PageHeight>11in</PageHeight>" +
                "  <MarginTop>0.5in</MarginTop>" +
                "  <MarginLeft>0.5in</MarginLeft>" +
                "  <MarginRight>0.5in</MarginRight>" +
                "  <MarginBottom>0.5in</MarginBottom>" +
                "</DeviceInfo>";

            Warning[] warnings;
            string[] streams;
            byte[] renderedBytes;

            renderedBytes = lr.Render(reportType, deviceInfo, out mimeType, out encoding, out fileNameExtension, out streams, out warnings);
            return File(renderedBytes, mimeType);

            //List<object> dataList = (List<object>)ls;
            //return Print("~/Reports/rptCustomer.rdlc", "dtCustomer", dataList);
        }

        //
        // GET: /Reports/CustomerLedger

        [HttpGet]
        public ActionResult CustomerLedger()
        {
            //--- Get Parameters
            int id = Convert.ToInt32(this.Request.QueryString["CustomerId"]);
            string fromd = this.Request.QueryString["From"];
            string tod = this.Request.QueryString["To"];

            Customer cs = db.Customer.Select(x => x).Where(x => x.CustomerID == id).FirstOrDefault();

            if (cs.Address == null)
            {
                cs.Address = "-";
            }
            if (cs.City == null)
            {
                cs.City = "-";
            }

            //--- Set Report Parameters
            ReportParameter rp1 = new ReportParameter("From", fromd);
            ReportParameter rp2 = new ReportParameter("To", tod);
            ReportParameter rp3 = new ReportParameter("Name", cs.Name);
            ReportParameter rp4 = new ReportParameter("Address", cs.Address);
            ReportParameter rp5 = new ReportParameter("Contact", cs.Contact + ", " + cs.Contact1 + ", " + cs.Contact2 + ", " + cs.Contact3);
            ReportParameter rp6 = new ReportParameter("City", cs.City);
            
            LocalReport lr = new LocalReport();
            lr.ReportPath = Server.MapPath("~/Reports/rptCustomerLedger.rdlc");
            DateTime fromDate, toDate;

            try
            {
                fromDate = Convert.ToDateTime(fromd);
                toDate = Convert.ToDateTime(tod);
            }
            catch (Exception)
            {
                return HttpNotFound("From or To Date cannot be null");
            }

            var param_CustomerId = new SqlParameter("@CustomerId", id);
            var ledger = db.Database.SqlQuery<Ledger>("SP_CustomerLedger @CustomerId", param_CustomerId).ToList();

            var ls = ledger.Select(x => x).Where(z => z.Date >= fromDate && z.Date <= toDate);

            ReportDataSource rd = new ReportDataSource("dtCustomerLedger", ls.ToList());
            lr.DataSources.Add(rd);
            lr.SetParameters(new ReportParameter[] { rp1, rp2, rp3, rp4, rp5, rp6 });

            string reportType = "pdf";
            string mimeType;
            string encoding;
            string fileNameExtension;
            string deviceInfo =
                "<DeviceInfo>" +
                "  <OutputFormat>PDF</OutputFormat>" +
                "  <PageWidth>8.5in</PageWidth>" +
                "  <PageHeight>11in</PageHeight>" +
                "  <MarginTop>0.5in</MarginTop>" +
                "  <MarginLeft>0.4in</MarginLeft>" +
                "  <MarginRight>0.4in</MarginRight>" +
                "  <MarginBottom>0.5in</MarginBottom>" +
                "</DeviceInfo>";

            Warning[] warnings;
            string[] streams;
            byte[] renderedBytes;

            renderedBytes = lr.Render(reportType, deviceInfo, out mimeType, out encoding, out fileNameExtension, out streams, out warnings);
            return File(renderedBytes, mimeType);
        }


        //
        // GET: /Reports/RptInvoice

        [HttpGet]
        public ActionResult RptInvoice( ) {

            try {
                int id = 0;
                try {
                    string[] Url = this.Request.Path.Split( '/' );
                    id = Convert.ToInt32( Url[( Url.Length - 1 )] );
                } catch( Exception ) {
                    return HttpNotFound( "There was an Error in your Request, Please Contact Software Vendor" );
                }

                Invoice inv = db.Invoices.Select( x => x ).Where( x => x.InvoiceID == id ).FirstOrDefault( );
                if( inv==null ) {
                    return HttpNotFound( "Could Not Find Invoice #" + id );
                }

                ////--- Set Report Parameters
                //ReportParameter rp1 = new ReportParameter( "InvoiceId", inv.InvoiceID.ToString( ) );
                //ReportParameter rp2 = new ReportParameter( "BillNo", inv.BillNo );
                //ReportParameter rp3 = new ReportParameter( "Name", inv.Cus.Name );
                //ReportParameter rp4 = new ReportParameter( "Address", inv.Cus.Address );
                //ReportParameter rp5 = new ReportParameter( "Contact", inv.Cus.Contact + ", " + inv.Cus.Contact1 + ", " +
                //        inv.Cus.Contact2 + ", " + inv.Cus.Contact3 );
                //ReportParameter rp6 = new ReportParameter( "City", inv.Cus.City );
                //ReportParameter rp7 = new ReportParameter( "Date", inv.Date.ToString( ) );
                //ReportParameter rp8 = new ReportParameter( "OBalance", inv.Cus.OpeningBalance.ToString( ) );
                //ReportParameter rp9 = new ReportParameter( "Total", inv.GAmount.ToString( ) );
                //ReportParameter rp0 = new ReportParameter( "Rece", ( inv.Received * -1 ).ToString( ) );
                //ReportParameter rpx = new ReportParameter( "Balance", inv.Balance.ToString( ) );

                LocalReport lr = new LocalReport( );
                lr.ReportPath = Server.MapPath( "~/Reports/rptCustomerInv.rdlc" );

                 //db.InvoicesDetails.Select(x=>x)

                var ls = db.InvoicesDetails.Where( x => x.Invid == inv.InvoiceID ).Join(
                        db.Invoices,
                        comp => comp.Invid,
                        sect => sect.InvoiceID,
                        ( comp, sect ) => new { comp, sect } )
                    .Join(
                        db.Customer.Where( dsi => dsi.CustomerID == inv.CSId ),
                        cs => cs.sect.CSId,
                        dsi => dsi.CustomerID,
                        ( cs, dsi ) => new { cs, dsi } )
                    .Select( c => new {
                        c.cs.comp.Id, c.cs.comp.Inv, c.cs.comp.Invid, c.cs.comp.Item, c.cs.comp.Price, c.cs.comp.Quantity,
                        c.cs.comp.Total, c.cs.sect.Balance, c.cs.sect.BillNo, c.cs.sect.CSId, c.cs.sect.Cus, c.cs.sect.Date,
                        c.cs.sect.GAmount, c.cs.sect.InvoiceID, c.cs.sect.Received, c.dsi.Address, c.dsi, c.dsi.City,
                        c.dsi.CustomerID, c.dsi.Name, c.dsi.OpeningBalance, c.dsi.AlertStatus, c.dsi.AlertDays, c.dsi.PendingDate,
                        c.dsi.Contact, c.dsi.Contact1, c.dsi.Contact2, c.dsi.Contact3
                    } );



                ReportDataSource rd = new ReportDataSource( "dsCustInv", ls.ToList( ) );
                lr.DataSources.Add( rd );

                string reportType = "pdf";
                string mimeType;
                string encoding;
                string fileNameExtension;
                string deviceInfo =

Views/Ledger/ChequesToday.cshtml
@model IEnumerable<ams.Models.Cheques>

@{
    ViewBag.Title = "Cheques Today";
}

<h2 style="margin-top:0px;margin-bottom:20px;">Cheques Today</h2>

<table class="table table-striped table-bordered table-hover">
    <tr>
        <th>
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CustomerName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Particular)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BillNo)
        </th>
        <th>
            Amount
        </th>
    </tr>

@foreach (var item in Model)
{
    <tr>
        <td>
            @Html.CheckBox("a", new { @id = item.Id, @class = "chk" })
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CustomerName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Particular)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BillNo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.amount)
        </td>
    </tr>
}

</table>
<p>
    <input id="btnPending" type="submit" style="margin-left:5px;" value="Mark as Seen" />
</p>
@section Scripts {
    <script type="text/javascript">

        $(document).ready(function ()
        {
            $('#btnPending').click(function ()
            {
                var ids = new Array();
                var cnt = 0;
                if ($('.chk:checked').length <= 0) {
                    alert("Please select Cheques to ignore");
                    return;
                }

                $('.chk').each(function ()
                {
                    if ($(this).prop('checked'))
                    {
                        ids[cnt] = parseInt($(this).attr("id"));
                        cnt++;
                    }
                });

                var idsToSend = JSON.stringify(ids);

                $.ajax({
                    contentType: 'application/json; charset=utf-8',
                    type: 'POST',
                    url: '@Url.Content("~/Ledger/Seen/")',
                    data: idsToSend,
                    dataType: "json",
                    success: function (data) {
                        window.location.replace("@Url.Content("~/Ledger/ChequesToday")");
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        alert(thrownError + ' ' + xhr.status);
                    }
                });
            });
           
        });

    </script>
}

Views/Ledger/Create.cshtml
@model ams.Models.Ledger

@{
    ViewBag.Title = "Create Ledger";
}

<style>
    .editor-field {
        margin-bottom:10px;
    }

</style>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset style="padding-left:10px;">
        <legend>Ledger</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Date)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Date)
            @Html.ValidationMessageFor(model => model.Date)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.BillNo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.BillNo)
            @Html.ValidationMessageFor(model => model.BillNo)
        </div>

        <div class="editor-field">
            @Html.HiddenFor(model => model.CustomerId, new { Value = ViewBag.Customerid })
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Particular)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Particular)
            @Html.ValidationMessageFor(model => model.Particular)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Debit)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Debit, new { @id="txtDebit", @Value="0" })
            @Html.ValidationMessageFor(model => model.Debit)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Credit)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Credit, new { @id="txtCredit", @Value="0" })
            @Html.ValidationMessageFor(model => model.Credit)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.isCheque)
        </div>
        <div class="editor-field">
            @Html.DropDownList("isCheque", new List<SelectListItem>{
                new SelectListItem{ Text="No", Value = "0" },
                new SelectListItem{ Text="Yes", Value = "1" }
             }) 
        </div>

@*        <div class="editor-label">
            @Html.LabelFor(model => model.Balance)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Balance, new { @id="txtBalance", @readonly="readonly", @Value=ViewBag.Balance, @Style="background-color:#eee;"  })
        </div>

        <div class="editor-label">
            <strong>Previous Balance</strong>
        </div>
        <div class="editor-field">
             @Html.TextBox("PrevBalance","", new { @id="txtPrevBalance", @type="text", @readonly="true", @Value=ViewBag.Balance, @Style="background-color:#eee;" })
        </div>*@

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

@section Scripts {
    <script type="text/javascript">

        $(document).ready(function () {

            //$('#txtDebit').change(function () {
            //    $('#txtCredit').val('0');
            //    var balance = parseInt($('#txtPrevBalance').val()) - parseInt($('#txtDebit').val());
            //    $('#txtBalance').val(balance);
            //});

            //$('#txtCredit').change(function () {
            //    $('#txtDebit').val('0');
            //    var balance = parseInt($('#txtPrevBalance').val()) + parseInt($('#txtCredit').val());
            //    $('#txtBalance').val(balance);
            //});

        });

    </script>
}

Views/Ledger/CustomerLedger.cshtml
@model IEnumerable<ams.Models.Ledger>

@{
    ViewBag.Title = "Customer Ledger";
}

<h2 style="margin-top:0;font-weight:bold;font-size:26px;">@ViewBag.Name</h2>
<strong style="display:inline-block;margin-bottom:5px;">@ViewBag.Address</strong><br />
<strong>@ViewBag.Contacts</strong>

<p>
    @Html.ActionLink("Create New Entry", "Create", "Ledger", new { id=ViewBag.Customerid }, null) | 
    @Html.ActionLink("Print", "RptLedger", "Ledger", new { id=ViewBag.Customerid }, null)
    
    <strong style="float:right;">Opening Balance : @ViewBag.OpeningBalance</strong>

</p>
<table class="table table-striped table-bordered table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BillNo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Particular)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Debit)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Credit)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Balance)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BillNo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Particular)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Debit)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Credit)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Balance)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.LedgerID }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.LedgerID })
        </td>
    </tr>
}

</table>
@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $(window).load(function () {
                $("html, body").animate({
                    scrollTop: $(document).height()
                }, 1000);
            });
        });
    </script>
}

Views/Ledger/Edit.cshtml
@model ams.Models.Ledger

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Ledger</legend>

        @Html.HiddenFor(model => model.LedgerID)

        <div class="editor-label">
            @Html.LabelFor(model => model.Date)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Date, new { Type="date", Id="Date"})
            @Html.ValidationMessageFor(model => model.Date)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.BillNo)
        </div>

        <div class="editor-field">
            @Html.EditorFor(model => model.BillNo)
            @Html.ValidationMessageFor(model => model.BillNo)
        </div>

        <div class="editor-field">
            @Html.HiddenFor(model => model.CustomerId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Particular)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Particular)
            @Html.ValidationMessageFor(model => model.Particular)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Debit)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Debit)
            @Html.ValidationMessageFor(model => model.Debit)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Credit)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Credit)
            @Html.ValidationMessageFor(model => model.Credit)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.isCheque)
        </div>
        <div class="editor-field">
            @Html.DropDownList("isCheque", new List<SelectListItem>{
                new SelectListItem{ Text="No", Value = "0" },
                new SelectListItem{ Text="Yes", Value = "1" }
             }) 
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}
<div>
    @Html.ActionLink("Back to List", "Index", "Customer")
</div>

@section Scripts {
    <script type="text/javascript">

        $(document).ready(function ()
        {
            var now = new Date( "@Model.Date" );
            var day = ("0" + now.getDate()).slice(-2);
            var month = ("0" + (now.getMonth() + 1)).slice(-2);
            var today = now.getFullYear() + "-" + (month) + "-" + (day);
            $('input#Date').val(today);
        });

    </script>
}

Views/Ledger/Index.cshtml
@model IEnumerable<ams.Models.Ledger>

@{
    ViewBag.Title = "Ledger";
}

<h2>Ledger</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

Views/Ledger/RptLedger.cshtml
@model ams.Models.Ledger

@{
    ViewBag.Title = "Print Ledger";
}

<style>
    .editor-field {
        margin-bottom:10px;
    }

</style>

@using (Html.BeginForm("CustomerLedger", "Reports", FormMethod.Get, null))
{
    @Html.ValidationSummary(true)

    <fieldset style="padding-left:10px;">
        <legend>Print Ledger</legend>

        <div class="editor-field">
            @Html.HiddenFor(model => model.CustomerId, new { Value = ViewBag.Customerid })
        </div>

        <div class="editor-label">
            <label>From Date:</label>
        </div>
        <div class="editor-field">
            @Html.TextBox("From", null, new { @Id = "FROM", @type="date", @Value=DateTime.Now.ToString("mm/dd/yyyy") })
        </div>

        <div class="editor-label">
            <label>To Date:</label>
        </div>
        <div class="editor-field">
            @Html.TextBox("To", null, new { @Id = "TO", @type="date", @Value=DateTime.Now.ToString("mm/dd/yyyy") })
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section Scripts {
    <script type="text/javascript">

        $(document).ready(function ()
        {
            var now = new Date("@DateTime.Now");
            var day = ("0" + now.getDate()).slice(-2);
            var month = ("0" + (now.getMonth() + 1)).slice(-2);
            var today = now.getFullYear() + "-" + (month) + "-" + (day);
            $('input#TO').val(today);

            now = new Date("@DateTime.Now.AddMonths(-6)");
            day = ("0" + now.getDate()).slice(-2);
            month = ("0" + (now.getMonth() + 1)).slice(-2);
            today = now.getFullYear() + "-" + (month) + "-" + (day);
            $('input#FROM').val(today);
        });
    </script>
}